framework:
  - name: pytorch                                # possible values are tensorflow, mxnet and pytorch

tuning:
  metric:
    topk: 1                                  # tuning metrics: accuracy 
  accuracy_criterion:
    - relative: 0.01                           # the tuning target of accuracy loss percentage: 1%
  timeout: 0                                   # tuning timeout (seconds)
  random_seed: 9527                            # random seed
  ops: {
           'module.features.stemblock.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock1.denselayer1.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock1.denselayer2.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock1.denselayer3.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock2.denselayer1.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock2.denselayer2.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock2.denselayer3.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock2.denselayer4.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer1.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer2.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer3.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer4.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer5.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer6.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer7.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock3.denselayer8.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock4.denselayer1.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock4.denselayer2.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock4.denselayer3.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock4.denselayer4.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock4.denselayer5.f_cat': {
             'activation':  {'dtype': ['fp32']},
           },
           'module.features.denseblock4.denselayer6.f_cat': {
             'activation':  {'dtype': ['fp32']}
           }
         }

calibration:
    dataloader:
      batch_size: 256
      dataset:
        - type: "ImageFolder"
        - root: /Path/to/imagenet/img/val
      transform:
        RandomResizedCrop:
          - size: 224
        RandomHorizontalFlip:
        ToTensor:
        Normalize:
          - mean: [0.485, 0.456, 0.406]
          - std: [0.229, 0.224, 0.225]

evaluation:
  dataloader:
    batch_size: 256
    dataset:
      - type: "ImageFolder"
      - root: /Path/to/imagenet/img/val
    transform:
      Resize:
        - size: 256
      CenterCrop:
        - size: 224
      ToTensor:
      Normalize:
        - mean: [0.485, 0.456, 0.406]
        - std: [0.229, 0.224, 0.225]
