#
# Copyright (c) 2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

model:
  name: imagenet_prune
  framework: pytorch

pruning:
  train:
    start_epoch: 0
    end_epoch: 4
    dataloader:
      batch_size: 30
      dataset:
        ImageFolder:
          root: /path/to/training/dataset
    optimizer:
      SGD:
        learning_rate: 0.1
        momentum: 0.1
        nesterov: True
        weight_decay: 0.1
    criterion:
      CrossEntropyLoss:
        reduction: Sum
  approach:
    weight_magnitude:
      initial_sparsity: 0.0
      target_sparsity: 0.97
      modifiers:
        - !MagnitudePruneModifier
            start_epoch: 1
            end_epoch: 3
            mask_type: unstructured
            params: ['layer1.0.conv1.weight']

        - !MagnitudePruneModifier
            start_epoch: 0
            end_epoch: 4
            target_sparsity: 0.6
            mask_type: unstructured
            update_frequency: 2
            params: ['layer1.0.conv2.weight']

tuning:
  metric:
    topk: 1                                    # tuning metrics: accuracy 
  accuracy_criterion:
    - relative: 0.01                           # the tuning target of accuracy loss percentage: 1%
  timeout: 0                                   # tuning timeout (seconds)
  random_seed: 9527                            # random seed
