framework:
    name: tensorflow                              # possible values are tensorflow, mxnet and pytorch
    inputs: image_tensor
    outputs: num_detections,detection_boxes,detection_scores,detection_classes

calibration:
    iterations: 1, 5, 10, 20
    algorithm:
        weight: minmax
        activation: minmax

tuning:
    accuracy_criterion:
        relative: 0.02                              # the tuning target of accuracy loss percentage: 2%
    timeout: 0                                      # tuning timeout (seconds)
    random_seed: 9527                               # random seed

evaluation:
    dataloader:
        batch_size: 1
        dataset:
            type: "TFRecordDataset"
            root: "./data/tf_val2017/coco_val.record" # Path to your TF Record COCO Dataset
        transform:
          Resize:
              size: 256
          CenterCrop:
              size: 224
