framework:
    name: tensorflow                              # possible values are tensorflow, mxnet and pytorch
    inputs: input
    outputs: MobilenetV1/Predictions/Reshape_1

dataloader:
  batch_size: 10
  dataset:
      type: "Imagenet"
      root: "./small_dataset" # NOTICE: config to your content images path
  transform:
      ParseDecodeImagenet:
      BilinearImagenet: 
          height: 224
          width: 224

calibration:                                         
  iterations: 2,5
  algorithm:  
    activation: minmax

quantization: 
    weight:
        granularity: per_channel

tuning:
    metric:  
        topk: 1
    accuracy_criterion:
        relative: 0.02                              # the tuning target of accuracy loss percentage: 2%
    timeout: 0                                      # tuning timeout (seconds)
    random_seed: 9527                               # random seed                       

