framework:
    name: tensorflow                              # possible values are tensorflow, mxnet and pytorch
    inputs: input_tensor
    outputs: softmax_tensor

dataloader:
  batch_size: 10
  dataset:
      type: "Imagenet"
      root: "./small_dataset" # NOTICE: config to your content images path
  transform:
      ParseDecodeImagenet:
      ResizeCropImagenet: 
          height: 224
          width: 224
          mean_value: [123.68, 116.78, 103.94]

calibration:                            
  iterations: 5, 10
  algorithm:
    activation: minmax

benchmark:                            
  dataloader:
    batch_size: 1

tuning:
    random_seed: 9527                               # random seed                       
    metric:  
        topk: 1
    accuracy_criterion:
        relative: 0.01                             # the tuning target of accuracy loss percentage: 1%
    timeout: 0                                      # tuning timeout (seconds)

